### ISSUE TITLE
panic after go get

### ISSUE THREAD

**Issue by AlexFinn** [justjanne/powerline-go#159]
macOS Catalina

```
go version go1.13.4 darwin/amd64
```

```
> ~/go/bin/powerline-go                                                                                                                                             16:47:16
panic: exit status 128

goroutine 1 [running]:
main.segmentGit(0xc0000e6000)
	/Users/alx/go/src/github.com/justjanne/powerline-go/segment-git.go:142 +0x6bd
main.newPowerline(0xc000066550, 0xc00008e6a0, 0xc00008e6a8, 0xc00008e6b2, 0xc00008e6b3, 0xc00008e6b4, 0xc00008e6b5, 0xc000066560, 0xc000066570, 0xc000066580, ...)
	/Users/alx/go/src/github.com/justjanne/powerline-go/powerline.go:88 +0x603
main.main()
	/Users/alx/go/src/github.com/justjanne/powerline-go/main.go:279 +0x1d13
panic: exit status 128

goroutine 1 [running]:
main.segmentGit(0xc0000ea380)
	/Users/alx/go/src/github.com/justjanne/powerline-go/segment-git.go:142 +0x6bd
main.newPowerline(0xc000068540, 0xc0000906a0, 0xc0000906a8, 0xc0000906b2, 0xc0000906b3, 0xc0000906b4, 0xc0000906b5, 0xc000068550, 0xc000068560, 0xc000068570, ...)
	/Users/alx/go/src/github.com/justjanne/powerline-go/powerline.go:88 +0x603
main.newPowerline(0xc000068540, 0xc0000906a0, 0xc0000906a8, 0xc0000906b2, 0xc0000906b3, 0xc0000906b4, 0xc0000906b5, 0xc000068550, 0xc000068560, 0xc000068570, ...)
	/Users/alx/go/src/github.com/justjanne/powerline-go/powerline.go:77 +0x4fc
main.main()
	/Users/alx/go/src/github.com/justjanne/powerline-go/main.go:279 +0x1d13
```

**Comment by justjanne** [comment]
This is fixed in the latest build.

**Comment by AlexFinn** [comment]
Thanks
