### ISSUE TITLE
cwd-max-dir-size throws error

### ISSUE THREAD

**Issue by Naatan** [justjanne/powerline-go#9]
First off - thanks for the great prompt!

That said, I used `-cwd-max-dir-size 3` and received this error:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x55bf40, 0xc8200140e0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
main.segmentCwd(0xc8200be000)
	/home/travis/gopath/src/github.com/justjanne/powerline-go/segment-cwd.go:121 +0xc5a
main.main()
	/home/travis/gopath/src/github.com/justjanne/powerline-go/main.go:125 +0x559  
```

**Comment by justjanne** [comment]
I just fixed it a minute ago, could you try again now?

**Comment by Naatan** [comment]
Works now - thanks!
